BundleAdjustment:
  thres_loss_function: 1.0

RelPoseEstimation:
  max_epipolar_error: 1.0

GlobalPositioning:
  thres_loss_function: 0.10000000000000001

Triangulation:
  complete_max_reproj_error: 15.0
  merge_max_reproj_error: 15.0  
  min_angle: 1.0
  min_num_matches: 15
    
Thresholds:
  max_angle_error: 1.0
  max_reprojection_error: 0.01
  min_triangulation_angle: 1.0
  min_inlier_num: 30.0
  min_inlier_ratio: 0.25
  max_rotation_error: 10.0
  max_epipolar_error_E: 1.0
  max_epipolar_error_F: 4.0
  max_epipolar_error_H: 4.0

feature_extractor:
  SiftExtraction_num_octaves: 4
  SiftExtraction_octave_resolution: 3
  SiftExtraction_peak_threshold: 0.0066666666666666671
  SiftExtraction_edge_threshold: 10.0
  SiftExtraction_dsp_min_scale: 0.1666666666666666
  SiftExtraction_dsp_max_scale: 3.0
  SiftExtraction_dsp_num_scales: 10

matcher:
  SiftMatching_max_ratio: 0.80000000000000004
  SiftMatching_max_distance: 0.69999999999999996
  TwoViewGeometry_min_num_inliers: 15
  TwoViewGeometry_max_error: 4.0
  TwoViewGeometry_confidence: 0.999
  TwoViewGeometry_min_inlier_ratio: 0.25
  SequentialMatching_overlap: 10
  SequentialMatching_quadratic_overlap: 1 
  ExhaustiveMatching_block_size: 50
